
Vagrant.configure("2") do |config|
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
  end

  # Specify a valid CentOS box (e.g., centos/7 or centos/stream8)
  config.vm.box = "centos/7"

  # Provision the VM using a shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install epel-release -y
    sudo yum install ansible -y
  SHELL
end
